(35, 'Unknown SSL protocol error in connection to api.github.com:443 ')
(28, 'Operation timed out after 80002 milliseconds with 241216 out of 340792 bytes received')
21483441 crawler success
29 crawler success
5993630 crawler success
18045249 crawler success
(28, 'Operation timed out after 80000 milliseconds with 547203 out of 571277 bytes received')
(28, 'Operation timed out after 80000 milliseconds with 3808872 out of 4337635 bytes received')
(28, 'Operation timed out after 80000 milliseconds with 3948164 out of 4337635 bytes received')
(28, 'Operation timed out after 80010 milliseconds with 238641 out of 337156 bytes received')
8149324 crawler success
Traceback (most recent call last):
  File "issues_get.py", line 92, in <module>
    issues_get()
  File "issues_get.py", line 32, in issues_get
    repo_id=repo.split(" ")[0]
AttributeError: 'NoneType' object has no attribute 'split'
